version: "3.8"

name: "liquidai-demo"

services:
  
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - "5173:5173"
    environment:
      - BACKEND_URL=http://backend:3001/
