name: CI pipeline

on:
  pull_request:
    types: [opened, reopened]
    branches:    
      - main

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm run install:frontend

      - name: Check style
        run: npm run lint:frontend
      
      - name: Build Project
        run: npm run build:frontend

      - name: Run tests
        run: npm run ci-test:frontend
      
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm run install:backend

      - name: Check style
        run: npm run lint:backend
      
